print("my name is mari")
print("skz4thgenleaders")
print("leeknowoutdance4thgen")
print("changbin is the besr raper in 4thgen")
print("hyunjin4thgrnitboy")
print("yakamoz")
print("3RACHA")
print("danceracha")
print("vocalracha")
print("paboracha")
print("waxingracha")
print("maknae on top")
print("JJAM")
print("levanter")
print("maze of memories")
print("side effects")
print("double knot")
print("District 9")
print("the tortoise and the hare")
print("give me your TMI")